In [1]:
# Load dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from lifelines import KaplanMeierFitter
from lifelines.plotting import add_at_risk_counts

# Set pandas option to display all columns
pd.set_option('display.max_columns', None)

##### **Licals**

In [2]:
lical1 = pd.read_csv('/Users/Apple/projects/ALS_Digital_Twins/03_LICALS_Trial/Results/07_LICALS_Data_EDA.csv')
print(lical1.columns)

Index(['subject_id', 'Event', 'Vital_capacity', 'El_Escorial', 'Sex', 'Height',
       'Onset_site', 'Study_Arm', 'European', 'diag_to_death', 'Age_Rand',
       'Age_Onset', 'Lithum_use', 'Diagnostic_Delay', 'Study_Duration',
       'Age_Diag', 'Enrollment_Delay', 'onset_to_death', 'Stage', 'ALSFRS_RT',
       'ALSFRS_Rasch', 'onset_site_cat', 'ftd', 'dxdelay', 'slope', 'tAge',
       'tdxdelay', 'minus_slope', 'tslope', 'tfvc', 'TRICALS', 'Onset_to_Rand',
       'Age.', 'Height.', 'ALSFRS_RT.', 'ALSFRS_Rasch.', 'Diagnostic_Delay.',
       'TRICALS.'],
      dtype='object')

In [3]:

lical1.head(3)

,subject_id,Event,Vital_capacity,El_Escorial,Sex,Height,Onset_site,Study_Arm,European,diag_to_death,Age_Rand,Age_Onset,Lithum_use,Diagnostic_Delay,Study_Duration,Age_Diag,Enrollment_Delay,onset_to_death,Stage,ALSFRS_RT,ALSFRS_Rasch,onset_site_cat,ftd,dxdelay,slope,tAge,tdxdelay,minus_slope,tslope,tfvc,TRICALS,Onset_to_Rand,Age.,Height.,ALSFRS_RT.,ALSFRS_Rasch.,Diagnostic_Delay.,TRICALS.
0,P01001,0,107.0,0,Male,171.0,Limb,Placebo,1,30.958607,54.762491,51.967146,Yes,5.880420,19.000000,52.457221,27.660972,34.831143,4,35.0,25.7,0,0,6.880420,-0.684211,3.702902,0.831665,0.684211,1.129233,1.901316,-4.129038,33.544148,-4.509445,-1.0,-5.0,-3.5,-4.530716,0.457426
1,P01002,1,99.0,0,Female,164.0,Limb,Placebo,1,27.562418,61.160849,59.613963,Yes,9.526938,19.528252,60.407940,9.034166,37.089356,4,43.0,32.2,0,0,10.526938,-0.256039,2.813870,1.026003,0.256039,1.675911,2.015139,-5.307470,18.562628,1.888913,-8.0,3.0,3.0,-0.884198,-0.721005
2,P01003,0,102.0,0,Male,182.0,Limb,Active,1,27.949409,46.702259,45.155373,Yes,4.960578,19.000000,45.568789,13.600526,32.763798,4,43.0,32.2,0,0,5.960578,-0.263158,4.904346,0.777839,0.263158,1.659404,1.970540,-5.260502,18.562628,-12.569677,10.0,3.0,3.0,-5.450558,-0.674037

In [4]:
lical = lical1[['subject_id', 'Event', 'Vital_capacity', 'Sex','El_Escorial', 'Onset_to_Rand',
       'Onset_site', 'Study_Arm', 'Age_Onset', 'Diagnostic_Delay', 'Study_Duration',
       'Age_Diag', 'Enrollment_Delay', 'ALSFRS_RT', 'ALSFRS_Rasch', 'slope']].copy()

lical['Disease_DurationD'] = lical1['diag_to_death']

# lical = lical.rename(columns={'Age_Rand': 'Age'})

lical = lical.copy()
# lical['European'] = 1
lical['Study_id'] = 'lica'
lical['Expt'] = 'licals'
lical.head(3)

,subject_id,Event,Vital_capacity,Sex,El_Escorial,Onset_to_Rand,Onset_site,Study_Arm,Age_Onset,Diagnostic_Delay,Study_Duration,Age_Diag,Enrollment_Delay,ALSFRS_RT,ALSFRS_Rasch,slope,Disease_DurationD,Study_id,Expt
0,P01001,0,107.0,Male,0,33.544148,Limb,Placebo,51.967146,5.880420,19.000000,52.457221,27.660972,35.0,25.7,-0.684211,30.958607,lica,licals
1,P01002,1,99.0,Female,0,18.562628,Limb,Placebo,59.613963,9.526938,19.528252,60.407940,9.034166,43.0,32.2,-0.256039,27.562418,lica,licals
2,P01003,0,102.0,Male,0,18.562628,Limb,Active,45.155373,4.960578,19.000000,45.568789,13.600526,43.0,32.2,-0.263158,27.949409,lica,licals

##### **Mirocals**

In [6]:
miro1 = pd.read_csv('/Users/Apple/projects/ALS_Digital_Twins/04_MIROCALS/Results/04_MIROCALS_Data_EDA.csv')
# print(miro1.columns)
miro1.head(3)

,COUNTRY_ID,ID,C9,SEX,AGEONSET_C,AGEDIAG_C,AGEINC_C,AGERANDO_C,RECLIFE,STATUS,INC_SITE_ONSET,SVCHP_INC,INC_DIAG,ARM_C,ALSFRS_RND,AGE_C,1. Speech_RD,2. Salivation_RD,3. Swallowing_RD,4. Handwriting_RD,5a. Cutting without gastrostomy_RD,6. Dressing and hygiene_RD,7. Turning in bed and adjusting bed clothes_RD,PNFHCSF_RD_3GTRT,8. Walking_RD,9. Climbing stairs_RD,10. Dyspnea_RD,11. Orthopnea_RD,12. Respiratory insufficiency_RD,End_diag_El_Escor,Stage_rnd,ALSFRS_Rasch,Onset_to_Rand,Study_Duration,Disease_Duration_rand,Diagnostic_delay,Onset_to_inclu,Diagnosis_to_inclu,Enrollment_Delay,onset_site_cat,ftd,dxdelay,slope,tAge,tdxdelay,minus_slope,tslope,tfvc,El_Escorial,TRICALS,Age.,ALSFRS_RND.,ALSFRS_Rasch.,Diagnostic_Delay.,TRICALS.
0,FR,1-62478,0.0,F,69.391,70.650,70.927,70.927,327.0,1.0,Limb,99.0,Clinically probable ALS - laboratory supported,Placebo,39.0,70.93,4.0,4.0,4.0,4.0,4.0,3.0,3.0,low,2.0,0.0,3.0,4.0,4.0,Clinically probable ALS,3.0,28.4,18.432,11.742444,29.174444,15.108,18.432,3.324,3.324,0,0,16.108,-0.766450,1.987819,1.264646,0.766450,1.074306,2.015139,0,-4.550056,11.217,-1.0,-0.8,6.222,0.129100
1,FR,1-62479,1.0,F,63.754,65.054,65.391,65.391,137.0,1.0,Bulbar,81.0,Clinically definite ALS,IL2,25.0,65.39,2.0,2.0,2.0,3.0,2.0,2.0,1.0,high,2.0,0.0,3.0,2.0,4.0,Clinically definite ALS,3.0,20.1,19.644,5.500657,24.144657,15.600,19.644,4.044,4.044,1,0,16.600,-4.181319,2.338644,1.282968,4.181319,0.483294,2.345679,1,-2.933660,5.681,-15.0,-9.1,6.714,1.745496
2,FR,1-62480,1.0,M,56.167,56.909,57.024,57.024,640.0,0.0,Limb,96.0,Clinically probable ALS,IL2,42.0,57.02,4.0,4.0,4.0,3.0,3.0,3.0,4.0,low,3.0,2.0,4.0,4.0,4.0,Clinically probable ALS,3.0,31.1,10.284,22.024967,31.308967,8.904,10.284,1.380,1.380,0,0,9.904,-0.272418,3.075280,0.995188,0.272418,1.638644,2.062287,0,-5.212384,-2.686,2.0,1.9,0.018,-0.533228

In [7]:
miro1.columns

Index(['COUNTRY_ID', 'ID', 'C9', 'SEX', 'AGEONSET_C', 'AGEDIAG_C', 'AGEINC_C',
       'AGERANDO_C', 'RECLIFE', 'STATUS', 'INC_SITE_ONSET', 'SVCHP_INC',
       'INC_DIAG', 'ARM_C', 'ALSFRS_RND', 'AGE_C', '1. Speech_RD',
       '2. Salivation_RD', '3. Swallowing_RD', '4. Handwriting_RD',
       '5a. Cutting without gastrostomy_RD', '6. Dressing and hygiene_RD',
       '7. Turning in bed and adjusting bed clothes_RD', 'PNFHCSF_RD_3GTRT',
       '8. Walking_RD', '9. Climbing stairs_RD', '10. Dyspnea_RD',
       '11. Orthopnea_RD', '12. Respiratory insufficiency_RD',
       'End_diag_El_Escor', 'Stage_rnd', 'ALSFRS_Rasch', 'Onset_to_Rand',
       'Study_Duration', 'Disease_Duration_rand', 'Diagnostic_delay',
       'Onset_to_inclu', 'Diagnosis_to_inclu', 'Enrollment_Delay',
       'onset_site_cat', 'ftd', 'dxdelay', 'slope', 'tAge', 'tdxdelay',
       'minus_slope', 'tslope', 'tfvc', 'El_Escorial', 'TRICALS', 'Age.',
       'ALSFRS_RND.', 'ALSFRS_Rasch.', 'Diagnostic_Delay.', 'TRICALS.'],
      dtype='object')

In [8]:
miro1.COUNTRY_ID.value_counts().to_dict()

{'FR': 137, 'UK': 83}

In [9]:
miro = miro1[['ID', 'SEX', 'AGEONSET_C', 'AGEDIAG_C', 'STATUS', 'INC_SITE_ONSET', 'SVCHP_INC', 'ARM_C', 'ALSFRS_RND', 'ALSFRS_Rasch','Onset_to_Rand',
       'Study_Duration', 'Diagnostic_delay', 'Enrollment_Delay', 'slope', 'El_Escorial']].copy()

miro['Disease_DurationD'] = miro1['Diagnosis_to_inclu'] + miro1['Study_Duration']

miro = miro.copy()
miro['Study_id'] = 'miro'
miro['Expt'] = 'mirocals'

miro.head(2)

,ID,SEX,AGEONSET_C,AGEDIAG_C,STATUS,INC_SITE_ONSET,SVCHP_INC,ARM_C,ALSFRS_RND,ALSFRS_Rasch,Onset_to_Rand,Study_Duration,Diagnostic_delay,Enrollment_Delay,slope,El_Escorial,Disease_DurationD,Study_id,Expt
0,1-62478,F,69.391,70.650,1.0,Limb,99.0,Placebo,39.0,28.4,18.432,11.742444,15.108,3.324,-0.766450,0,15.066444,miro,mirocals
1,1-62479,F,63.754,65.054,1.0,Bulbar,81.0,IL2,25.0,20.1,19.644,5.500657,15.600,4.044,-4.181319,1,9.544657,miro,mirocals

In [10]:
miro = miro.rename(columns={'ID': 'subject_id', 'AGEONSET_C': 'Age_Onset', 'AGEDIAG_C': 'Age_Diag', 'STATUS': 'Event', 'SVCHP_INC': 'Vital_capacity', 
                            'SEX': 'Sex', 'INC_SITE_ONSET': 'Onset_site', 'ARM_C': 'Study_Arm', 'Diagnostic_delay': 'Diagnostic_Delay', 'ALSFRS_RND': 'ALSFRS_RT'})

miro.head(3)

,subject_id,Sex,Age_Onset,Age_Diag,Event,Onset_site,Vital_capacity,Study_Arm,ALSFRS_RT,ALSFRS_Rasch,Onset_to_Rand,Study_Duration,Diagnostic_Delay,Enrollment_Delay,slope,El_Escorial,Disease_DurationD,Study_id,Expt
0,1-62478,F,69.391,70.650,1.0,Limb,99.0,Placebo,39.0,28.4,18.432,11.742444,15.108,3.324,-0.766450,0,15.066444,miro,mirocals
1,1-62479,F,63.754,65.054,1.0,Bulbar,81.0,IL2,25.0,20.1,19.644,5.500657,15.600,4.044,-4.181319,1,9.544657,miro,mirocals
2,1-62480,M,56.167,56.909,0.0,Limb,96.0,IL2,42.0,31.1,10.284,22.024967,8.904,1.380,-0.272418,0,23.404967,miro,mirocals

##### **Riluzole**

In [101]:
# rilu1 = pd.read_csv('/Users/Apple/Downloads/All_processed_data/riluzole_combined_data_tricals.csv')
# # print(rilu1.columns)
# print()
# # rilu1['Disease_Duration'] = rilu1['Study_Duration_months'] + rilu1['Diagnosis_delay']
# # rilu1.head(3)

In [102]:
# rilu = rilu1[['subject_id', 'Event', 'Vital_Capacity','Sex', 'Onset_site', 'Study_Arm','European',
#                 'Age', 'Diagnosis_delay',  'Disease_Duration','TRICALS_Risk_Profile','Study_id']]
# rilu = rilu.copy()
# rilu['Expt'] = 'riluzole'

# rilu = rilu.rename(columns={'Vital_Capacity': 'Vital_capacity', 'Diagnosis_delay': 'Diagnostic_Delay', 'TRICALS_Risk_Profile': 'TRICALS'})

# rilu.head(3)

In [103]:
# rilu.Sex.value_counts().to_dict()

In [11]:
print(lical.shape)
lical.head(2)

(214, 19)

,subject_id,Event,Vital_capacity,Sex,El_Escorial,Onset_to_Rand,Onset_site,Study_Arm,Age_Onset,Diagnostic_Delay,Study_Duration,Age_Diag,Enrollment_Delay,ALSFRS_RT,ALSFRS_Rasch,slope,Disease_DurationD,Study_id,Expt
0,P01001,0,107.0,Male,0,33.544148,Limb,Placebo,51.967146,5.880420,19.000000,52.457221,27.660972,35.0,25.7,-0.684211,30.958607,lica,licals
1,P01002,1,99.0,Female,0,18.562628,Limb,Placebo,59.613963,9.526938,19.528252,60.407940,9.034166,43.0,32.2,-0.256039,27.562418,lica,licals

In [12]:
print(miro.shape)
miro.head(2)

(220, 19)

,subject_id,Sex,Age_Onset,Age_Diag,Event,Onset_site,Vital_capacity,Study_Arm,ALSFRS_RT,ALSFRS_Rasch,Onset_to_Rand,Study_Duration,Diagnostic_Delay,Enrollment_Delay,slope,El_Escorial,Disease_DurationD,Study_id,Expt
0,1-62478,F,69.391,70.650,1.0,Limb,99.0,Placebo,39.0,28.4,18.432,11.742444,15.108,3.324,-0.766450,0,15.066444,miro,mirocals
1,1-62479,F,63.754,65.054,1.0,Bulbar,81.0,IL2,25.0,20.1,19.644,5.500657,15.600,4.044,-4.181319,1,9.544657,miro,mirocals

In [13]:
df_concat = pd.concat([lical, miro], ignore_index=True)
df_concat.head(3)

,subject_id,Event,Vital_capacity,Sex,El_Escorial,Onset_to_Rand,Onset_site,Study_Arm,Age_Onset,Diagnostic_Delay,Study_Duration,Age_Diag,Enrollment_Delay,ALSFRS_RT,ALSFRS_Rasch,slope,Disease_DurationD,Study_id,Expt
0,P01001,0.0,107.0,Male,0,33.544148,Limb,Placebo,51.967146,5.880420,19.000000,52.457221,27.660972,35.0,25.7,-0.684211,30.958607,lica,licals
1,P01002,1.0,99.0,Female,0,18.562628,Limb,Placebo,59.613963,9.526938,19.528252,60.407940,9.034166,43.0,32.2,-0.256039,27.562418,lica,licals
2,P01003,0.0,102.0,Male,0,18.562628,Limb,Active,45.155373,4.960578,19.000000,45.568789,13.600526,43.0,32.2,-0.263158,27.949409,lica,licals

In [14]:
df_concat.shape

(434, 19)

In [15]:
df_concat.to_csv('/Users/Apple/projects/ALS_Digital_Twins/All_processed_data/DataFIle/combined_other_datasets_for_modeling.csv', index=False)

In [16]:
df_concat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434 entries, 0 to 433
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   subject_id         434 non-null    object
 1   Event              434 non-null    float64
 2   Vital_capacity     434 non-null    float64
 3   Sex                434 non-null    object
 4   El_Escorial        434 non-null    int64
 5   Onset_to_Rand      434 non-null    float64
 6   Onset_site         434 non-null    object
 7   Study_Arm          434 non-null    object
 8   Age_Onset          434 non-null    float64
 9   Diagnostic_Delay   434 non-null    float64
 10  Study_Duration     434 non-null    float64
 11  Age_Diag           434 non-null    float64
 12  Enrollment_Delay   434 non-null    float64
 13  ALSFRS_RT          434 non-null    float64
 14  ALSFRS_Rasch       434 non-null    float64
 15  slope              434 non-null    float64
 16  Disease_DurationD  434 non-null    float64
 17  Study_id           434 non-null    object
 18  Expt               434 non-null    object
dtypes: float64(12), int64(1), object(6)
memory usage: 64.6+ KB